// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    String howManyTimes = args[0];
		int times = Integer.parseInt(howManyTimes);
        int count = 0; // counts how many random numbers have been generated
		int over = 0; // counts how many times we get a number > 0.5
		int less = 0; // counts how many times we get a number <= 0.5
		while (count < times) {
			double rand = Math.random();
			if (rand <= 0.5){
				less++;
			}else {
				over++;
			}
			count++;
          } 
		  System.out.println("> 0.5: " + over);
		  System.out.println("<= 0.5: " + less);
		}
	}
